repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: check-ast
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: github_deploy_key_ioos_erddapy.enc
    - id: check-docstring-first
    - id: check-added-large-files
      exclude_types: [yaml]
    - id: requirements-txt-fixer
    - id: file-contents-sorter
      files: requirements-dev.txt

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      exclude: ^(docs/source/conf.py|pyobis/obisissues.py)
      args: [--max-line-length=105]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      additional_dependencies: [toml]
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.1.1
  hooks:
  - id: mypy
    exclude: docs/source/conf.py
    entry: bash -c 'exec env CONDA_PREFIX="$(python -c "import sys; print(sys.executable)")"'
    args: ["--ignore-missing-imports", "--python-executable=CONDA_PREFIX"]

- repo: https://github.com/keewis/blackdoc
  rev: v0.3.8
  hooks:
    - id: blackdoc

- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
    - id: interrogate
      exclude: ^(docs|setup.py|tests|.*__init__.py)
      args: [-vv, --config=pyproject.toml]

# - repo: https://github.com/codespell-project/codespell
#   rev: v2.1.0
#   hooks:
#     - id: codespell
#       exclude: >
#           (?x)^(
#               .*\.yaml
#           )$
#       args:
#         - --quiet-level=2

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args:
        - --py36-plus

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.4.0
  hooks:
    - id: add-trailing-comma

# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.1.1
#   hooks:
#     - id: pydocstyle
#   exclude: ^(docs|setup.py)

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: false
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly
    skip: []
    submodules: false
